spring:
  test: "dev-test"

aws:
  s3:
    bucket:
      basic: ${AWS_BASIC_BUCKET}
      gpt: "landing-data-bucket-1220-16492640"
      logging:
    key:
      basic: ${AWS_BASIC_BUCKET_KEY}
      gpt: "Youtube/gpt-fun-facts/videoprompt.txt"
      logging: 
gpt:
  api:
    url: ${GPT_URL}
    key: ${API_KEY}
    model: "gpt-4"