spring:
  test: "dev-test"

aws:
  s3:
    bucket:
      basic: "landing-data-bucket-1220-16492640"
      gpt:
      logging:
    key:
      basic: "Youtube/fun-facts/Fact.json"
      gpt:
      logging: 
gpt:
  api:
    url: "https://api.openai.com/v1/chat/completions"
    key: ${API_KEY}
    model: "gpt-4"